### ISSUE TITLE
error[E0554]: #![feature] may not be used on the stable release channel

### ISSUE THREAD

**Issue by chrisminnick** [holochain/holochain-cmd#32]
Error installing holochain-cmd with rustc 1.29.0 (aa3ca1994 2018-09-11) on MacOS 10.13.6

Output:

chrisminnick$ cargo install -f --path .
  Installing hcdev v0.1.0 (file:///Users/chrisminnick/holochain-cmd)
    Updating registry `https://github.com/rust-lang/crates.io-index`
    Updating git repository `https://github.com/holochain/holochain-rust`       
 Downloading structopt v0.2.10                                                  
 Downloading serde_json v1.0.26                                                 
 Downloading failure v0.1.2                                                     
 Downloading assert_cmd v0.9.1                                                  
 Downloading colored v1.6.1                                                     
 Downloading serde v1.0.75                                                      
 Downloading serde_derive v1.0.75                                               
 Downloading ignore v0.4.3                                                      
 Downloading dir-diff v0.3.1                                                    
 Downloading uuid v0.6.5                                                        
 Downloading tempfile v3.0.3                                                    
 Downloading semver v0.9.0                                                      
 Downloading base64 v0.9.2                                                      
 Downloading structopt-derive v0.2.10                                           
 Downloading clap v2.32.0                                                       
 Downloading syn v0.14.9                                                        
 Downloading quote v0.6.8                                                       
 Downloading proc-macro2 v0.4.15                                                
 Downloading unicode-xid v0.1.0                                                 
 Downloading bitflags v1.0.4                                                    
 Downloading strsim v0.7.0                                                      
 Downloading ansi_term v0.11.0                                                  
 Downloading unicode-width v0.1.5                                               
 Downloading vec_map v0.8.1                                                     
 Downloading textwrap v0.10.0                                                   
 Downloading atty v0.2.11                                                       
 Downloading libc v0.2.43                                                       
 Downloading ryu v0.2.6                                                         
 Downloading indexmap v1.0.1                                                    
 Downloading itoa v0.4.2                                                        
 Downloading failure_derive v0.1.2                                              
 Downloading backtrace v0.3.9                                                   
 Downloading synstructure v0.9.0                                                
 Downloading cfg-if v0.1.5                                                      
 Downloading rustc-demangle v0.1.9                                              
 Downloading snowflake v1.3.0                                                   
 Downloading riker v0.1.7                                                       
 Downloading rust-base58 v0.0.4                                                 
 Downloading multihash v0.8.0                                                   
 Downloading lazy_static v1.1.0                                                 
 Downloading config v0.8.0                                                      
 Downloading unwrap_to v0.1.0                                                   
 Downloading num-traits v0.2.5                                                  
 Downloading num-derive v0.2.2                                                  
 Downloading riker-default v0.1.7                                               
 Downloading futures-preview v0.2.2                                             
 Downloading riker-patterns v0.1.7                                              
 Downloading chrono v0.4.6                                                      
 Downloading wasmi v0.3.0                                                       
 Downloading rand v0.4.3                                                        
 Downloading log v0.4.4                                                         
 Downloading bytes v0.4.9                                                       
 Downloading regex v0.2.11                                                      
 Downloading time v0.1.40                                                       
 Downloading num-integer v0.1.39                                                
 Downloading toml v0.4.6                                                        
 Downloading nom v3.2.1                                                         
 Downloading serde-hjson v0.8.1                                                 
 Downloading yaml-rust v0.4.0                                                   
 Downloading memchr v1.0.2                                                      
 Downloading num-traits v0.1.43                                                 
 Downloading serde v0.8.23                                                      
 Downloading linked-hash-map v0.3.0                                             
 Downloading regex v0.1.80                                                      
 Downloading lazy_static v0.2.11                                                
 Downloading serde_test v0.8.23                                                 
 Downloading memchr v0.1.11                                                     
 Downloading aho-corasick v0.5.3                                                
 Downloading regex-syntax v0.3.9                                                
 Downloading thread_local v0.2.7                                                
 Downloading utf8-ranges v0.1.3                                                 
 Downloading thread-id v2.0.0                                                   
 Downloading kernel32-sys v0.2.2                                                
 Downloading winapi v0.2.8                                                      
 Downloading winapi-build v0.1.1                                                
 Downloading linked-hash-map v0.5.1                                             
 Downloading version_check v0.1.4                                               
 Downloading futures-stable-preview v0.2.3                                      
 Downloading futures-executor-preview v0.2.2                                    
 Downloading futures-core-preview v0.2.3                                        
 Downloading futures-async-runtime-preview v0.2.3                               
 Downloading futures-util-preview v0.2.2                                        
 Downloading futures-channel-preview v0.2.2                                     
 Downloading futures-sink-preview v0.2.2                                        
 Downloading futures-io-preview v0.2.2                                          
 Downloading either v1.5.0                                                      
 Downloading num_cpus v1.8.0                                                    
 Downloading iovec v0.1.2                                                       
 Downloading byteorder v1.2.6                                                   
 Downloading thread_local v0.3.6                                                
 Downloading utf8-ranges v1.0.1                                                 
 Downloading aho-corasick v0.6.8                                                
 Downloading memchr v2.0.2                                                      
 Downloading regex-syntax v0.5.6                                                
 Downloading ucd-util v0.1.1                                                    
 Downloading num v0.2.0                                                         
 Downloading num-complex v0.2.0                                                 
 Downloading num-bigint v0.2.0                                                  
 Downloading num-rational v0.2.1                                                
 Downloading num-iter v0.1.37                                                   
 Downloading sha1 v0.5.0                                                        
 Downloading tiny-keccak v1.4.2                                                 
 Downloading sha2 v0.7.1                                                        
 Downloading crunchy v0.1.6                                                     
 Downloading fake-simd v0.1.2                                                   
 Downloading digest v0.7.5                                                      
 Downloading byte-tools v0.2.0                                                  
 Downloading block-buffer v0.3.3                                                
 Downloading generic-array v0.9.0                                               
 Downloading typenum v1.10.0                                                    
 Downloading arrayref v0.3.5                                                    
 Downloading riker-mapvec v0.1.7                                                
 Downloading riker-dispatcher v0.1.7                                            
 Downloading riker-timer v0.1.7                                                 
 Downloading riker-log v0.1.7                                                   
 Downloading riker-deadletter v0.1.7                                            
 Downloading futures-cpupool v0.1.8                                             
 Downloading futures v0.1.23                                                    
 Downloading runtime-fmt v0.3.0                                                 
 Downloading safemem v0.2.0                                                     
 Downloading parity-wasm v0.31.3                                                
 Downloading nan-preserving-float v0.1.0                                        
 Downloading memory_units v0.3.0                                                
 Downloading predicates-tree v0.9.0                                             
 Downloading escargot v0.3.1                                                    
 Downloading predicates-core v0.9.0                                             
 Downloading predicates v0.9.0                                                  
 Downloading treeline v0.1.0                                                    
 Downloading difference v2.0.0                                                  
 Downloading normalize-line-endings v0.2.2                                      
 Downloading regex v1.0.4                                                       
 Downloading float-cmp v0.4.0                                                   
 Downloading regex-syntax v0.6.2                                                
 Downloading crossbeam v0.3.2                                                   
 Downloading walkdir v2.2.5                                                     
 Downloading globset v0.4.1                                                     
 Downloading same-file v1.0.3                                                   
 Downloading fnv v1.0.6                                                         
 Downloading remove_dir_all v0.5.1                                              
 Downloading rand v0.5.5                                                        
 Downloading rand_core v0.2.1                                                   
 Downloading semver-parser v0.7.0                                               
   Compiling winapi-build v0.1.1                                                
   Compiling proc-macro2 v0.4.15
   Compiling either v1.5.0
   Compiling version_check v0.1.4
   Compiling libc v0.2.43
   Compiling unicode-xid v0.1.0
   Compiling winapi v0.2.8
   Compiling num-traits v0.2.5
   Compiling serde v1.0.75
   Compiling serde v0.8.23
   Compiling ryu v0.2.6
   Compiling typenum v1.10.0
   Compiling utf8-ranges v0.1.3
   Compiling num-integer v0.1.39
   Compiling regex-syntax v0.3.9
   Compiling itoa v0.4.2
   Compiling num-bigint v0.2.0
   Compiling regex v0.2.11
   Compiling linked-hash-map v0.5.1
   Compiling ucd-util v0.1.1
   Compiling indexmap v1.0.1
   Compiling lazy_static v0.2.11
   Compiling cfg-if v0.1.5
   Compiling num-complex v0.2.0
   Compiling num-rational v0.2.1
   Compiling num-iter v0.1.37
   Compiling utf8-ranges v1.0.1
   Compiling crunchy v0.1.6
   Compiling byteorder v1.2.6
   Compiling byte-tools v0.2.0
   Compiling futures v0.1.23
   Compiling regex v1.0.4
   Compiling arrayref v0.3.5
   Compiling safemem v0.2.0
   Compiling unicode-width v0.1.5
   Compiling fake-simd v0.1.2
   Compiling failure_derive v0.1.2
   Compiling escargot v0.3.1
   Compiling runtime-fmt v0.3.0
   Compiling fnv v1.0.6
   Compiling same-file v1.0.3
error[E0554]: #![feature] may not be used on the stable release channel
  --> /Users/chrisminnick/.cargo/registry/src/github.com-1ecc6299db9ec823/runtime-fmt-0.3.0/src/lib.rs:17:1
   |
17 | #![feature(fmt_internals)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: #![feature] may not be used on the stable release channel
  --> /Users/chrisminnick/.cargo/registry/src/github.com-1ecc6299db9ec823/runtime-fmt-0.3.0/src/lib.rs:18:1
   |
18 | #![feature(conservative_impl_trait)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: #![feature] may not be used on the stable release channel
  --> /Users/chrisminnick/.cargo/registry/src/github.com-1ecc6299db9ec823/runtime-fmt-0.3.0/src/lib.rs:19:1
   |
19 | #![feature(specialization)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: #![feature] may not be used on the stable release channel
  --> /Users/chrisminnick/.cargo/registry/src/github.com-1ecc6299db9ec823/runtime-fmt-0.3.0/src/lib.rs:20:1
   |
20 | #![feature(print_internals)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: #![feature] may not be used on the stable release channel
  --> /Users/chrisminnick/.cargo/registry/src/github.com-1ecc6299db9ec823/runtime-fmt-0.3.0/src/lib.rs:21:1
   |
21 | #![feature(rustc_private)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: #![feature] may not be used on the stable release channel
  --> /Users/chrisminnick/.cargo/registry/src/github.com-1ecc6299db9ec823/runtime-fmt-0.3.0/src/lib.rs:22:1
   |
22 | #![feature(try_from)]
   | ^^^^^^^^^^^^^^^^^^^^^

error: aborting due to 6 previous errors

For more information about this error, try `rustc --explain E0554`.
error: Could not compile `runtime-fmt`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `hcdev v0.1.0

**Comment by chrisminnick** [comment]
Resolved by solution from #29

**Comment by sophearyat** [comment]
we can solved it by use 
#cargo update
#cargo clean
#cargo run
