### ISSUE TITLE
Could not compile `hc`.

### ISSUE THREAD

**Issue by juliolrmonteiro** [holochain/holochain-cmd#65]
Hey guys, I am trying to build the latest version on master, but I get the following error:

`error[E0658]: The attribute `structopt` is currently unknown to the compiler and may have meaning added to it in the future (see issue #29642)
  --> src/main.rs:30:1
   |
30 | #[structopt(about = "A command line for Holochain")]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = help: add #![feature(custom_attribute)] to the crate attributes to enable

error: aborting due to 22 previous errors
`

All errors are related to this StructOps, that starts with this error:
`error: cannot find derive macro `StructOpt` in this scope==========> ] 184/185: hc                                     
  --> src/main.rs:29:10
   |
29 | #[derive(StructOpt)]
   |          ^^^^^^^^^

`

Should I be using a specific branch?

Cheers!

**Comment by Connoropolous** [comment]
My first guess is that you're not on nightly rust toolchain? As a default

**Comment by juliolrmonteiro** [comment]
Hey there @Connoropolous! Thanks for the quick reply! :)

I have used "rustup toolchain install nightly" before to compile and test "holochain-rust", would that do the trick?

Cheers!
Julio

**Comment by Connoropolous** [comment]
You need to do `rustup default nightly` too to ensure that the nightly
toolchain is the one that is used by default when you run cargo commands

**Comment by juliolrmonteiro** [comment]
Thank you, that nailed it!

**Comment by Connoropolous** [comment]
👍
