### ISSUE TITLE
Windows  can not run hc test. Plus first time using github!

### ISSUE THREAD

**Issue by theObama** [holochain/holochain-cmd#84]
After successfully compile the code. Bug discovered while trying to run `hc test` on Windows. It returns `Error: The system cannot find the file specified. (os error 2)`

![image](https://user-images.githubusercontent.com/31114376/47967942-40347880-e031-11e8-97af-3e4e887a9b12.png)

When trying to run `hc package`. It suppose to have a complete dna by filling in the zome. But nothing added. 
![image](https://user-images.githubusercontent.com/31114376/47967989-d4064480-e031-11e8-84cd-c211e99a5200.png)

Can anybody test on their Windows as well to see if they have the same issue?

**Comment by Connoropolous** [comment]
As an update, we resolved this particular issue. 

The problem was in fact that you cannot have a zome named `test`.
